#!/usr/bin/env python3
"""oc-traffic: OVN-Kubernetes network path visualizer for OpenShift."""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from oc_traffic.__main__ import main
sys.exit(main())
